[package]
name = "alacritty-toggle-themes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.204"
toml = "0.8.14"

[[bin]]
name = "atc"
path = "src/main.rs"
